name: Android CI

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Build & test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: JVM Setup
        uses: ./actions/jvm-setup

      - name: Assemble Android debug
        run: ./gradlew :composeApp:assembleDebug

      - name: Run tests
        run: ./gradlew test

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: success() || failure()
        with:
          annotate_only: true
          report_paths: "**/build/test-results/**/*.xml"
          fail_on_failure: true
