name: Android CI

on:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Build & test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: JVM Setup
        uses: gpunto/workflows/actions/jvm-setup@main

      - name: Build Android and test
        run: ./gradlew :composeApp:assembleDebug test

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: success() || failure()
        with:
          annotate_only: true
          report_paths: "**/build/test-results/**/*.xml"
          fail_on_failure: true
